votations/urls.py
from main.views import *
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
#from main.models import Acta
from rest_framework import routers, serializers, viewsets
#from votations.modelserializer import ActaSerializer
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.authtoken import views
from main.views import *


# class ActaViewSet(viewsets.ModelViewSet):
#     queryset = Acta.objects.all()
#     serializer_class = ActaSerializer

router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)
#router.register(r'Actas', ActaViewSet)
app_name = 'main'
urlpatterns = [
    path('',home.as_view(),name='home'),
    path('estadistica/',estadistica.as_view(),name='estadistica'),
    path('estadistica/filtrar', filtrar,name='estadistica-filtrar'),
    path('admin/', admin.site.urls),
    path('api/models/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),

    path('candidato/crear',CandidatoCreate.as_view(),name='candidato-add'),
    path('candidato/listar', CandidatoList.as_view(), name='candidato-list'),
    path('candidato/editar/<slug:pk>/',CandidatoUpdate.as_view(),name='candidato-update'),
    path('candidato/borrar/<slug:pk>/',CandidatoDelete.as_view(),name='candidato-delete'),

    path('candidatos/buscar', filtrar_candidatos,name='candidatos-buscar'),

    ##GUARDAR ELECCIONES
    path('votos/guardar', guardar_acta_escrutinio,name='escrutinio-guardar'),

    #path('acta/cambiarestado', cambiar_estado,name='acta-cambiar'),

    #path('acta/crear/<slug:pk>/',ActaCreate.as_view(),name='acta-add'),
    #path('acta/listar', ActaList.as_view(), name='acta-list'),
    #path('documentos/listar', TblDocumentList.as_view(), name='documento-list'),

    #path('documentosproceso/listar', ListProceso.as_view(), name='list-proceso'),

    path('escrutinio/crear/',EscrutinioCreate.as_view(),name='escrutinio-add'),
    path('escrutinio/listar', EscrutinioList.as_view(), name='escrutinio-list'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('escrutinio/<slug:pk>/', EscrutinioDetailView.as_view(), name='escrutinio-detail'),

    path('mesa/crear/',MesaCreate.as_view(),name='mesa-add'),
    path('mesa/listar', MesaList.as_view(), name='mesa-list'),

    path('colaborador/crear',ColaboradorCreate.as_view(),name='colaborador-add'),
    path('colaborador/editar/<slug:pk>/',ColaboradorUpdate.as_view(),name='colaborador-update'),
    path('votosg/imprimir/',votos_general ,name='votos-imprimir'),

    #REPORTE
    #path('reporte/escrutinio/',ReporteEscrutiniosExcel.as_view() ,name='escrutinios-excel'),
    url(r'^reporte/escrutinio/$',ReporteEscrutiniosExcel.as_view(), name="escrutinios-excel"),
    #url(r'^reporte_personas_excel/$',ReportePersonasExcel.as_view(), name="reporte_personas_excel"),
    #path('certificado/imprimir/(?P<alumno>\w{0,50})/(?P<grado>\w{0,50})/$',reporte_compras ,name='alumno-imprimir'),
    path('dashboard/', dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', pivot_data, name='pivot_data'),

]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.contrib.auth.models import AbstractUser

# Create your models here.
## Mesa
## Acta

class ModeloBase(models.Model):
    created_at =    models.DateTimeField(default=datetime.now(), blank=True)
    user_created =  models.ForeignKey(User,on_delete=models.CASCADE, related_name='%(class)s_requests_user_created')
    update_at =     models.DateTimeField(default=datetime.now(), blank=True)
    user_update =   models.ForeignKey(User,on_delete=models.CASCADE, related_name='%(class)s_requests_user_update')

    class Meta:
        abstract = True

class Departamento(models.Model):
    codigo = models.CharField(max_length=10)
    nombre = models.CharField(max_length=150)
    def __str__(self):
        return self.nombre

class Municipio(models.Model):
    codigo = models.CharField(max_length=10)
    nombre = models.CharField(max_length=150)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    def __str__(self):
        #return self.departamento.nombre + ' | ' +self.nombre
        return self.nombre

class Aldea(ModeloBase):
    codigo = models.CharField(max_length=10)
    nombre = models.CharField(max_length=150)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class Tipo(ModeloBase):
    nombre = models.CharField(max_length=150)
    descripcion  = models.CharField(max_length=150)

    def __str__(self):
        return self.nombre

class Corriente(ModeloBase):
    nombre = models.CharField(max_length=150)
    imagen = models.ImageField(upload_to='media/corriente')

    #candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Partido(ModeloBase):
    orden = models.IntegerField(default=1)
    nombre = models.CharField(max_length=40)
    logo = models.ImageField(upload_to='media/corriente')

    def __str__(self):
        return self.nombre

class Candidato(ModeloBase):
    GENDER_CHOICES = [
    ('F', 'Femenino'),
    ('M', 'Masculino'),
]
    departamento = models.ForeignKey(Departamento,related_name='departamento_candidatos', on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio,on_delete=models.CASCADE)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)
    partido = models.ForeignKey(Partido, on_delete=models.CASCADE)
    #corriente = models.ManyToManyField(Corriente, related_name='corriente_candidato')
    identidad = models.CharField(max_length=150, null = True)
    nombre = models.CharField(max_length=150)
    Sexo = models.CharField(
        max_length=15,
        choices=GENDER_CHOICES,
    )
    activo = models.BooleanField(default=True)
    casilla = models.IntegerField()
    #telefono = models.CharField(max_length=150)
    #email = models.EmailField(max_length=150,)
    #direccion = models.CharField(max_length=650,)
    foto = models.ImageField(upload_to='media/candidato',max_length=300)
    #grado = models.ForeignKey(Grado, on_delete=models.CASCADE)
    #clase = models.ManyToManyField(Clase)

    def __str__(self):
        return self.nombre + " - " +self.partido.nombre


class CentroEducativo(ModeloBase):
    departamento = models.ForeignKey(Departamento,related_name='departamento_centroeducativo', on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio,related_name='municipio_centroeducativo',on_delete=models.CASCADE)
    nombre = models.CharField(max_length=150)
    codigo = models.CharField(max_length=150)

    def __str__(self):
        return self.nombre
        #+ " - " + self.nombre

    def name_short(self):
        return "a"

#
# class Inscripcion(ModeloBase):
#     candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE)
#     corriente = models.ForeignKey(Corriente, on_delete= models.CASCADE)

class Mesa(ModeloBase):
    centro = models.ForeignKey(CentroEducativo,related_name='CentroEducativo',on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=150,null=True)
    numero = models.CharField(max_length=10)

    def __str__(self):
        return self.numero + " || " + str(self.centro.codigo) + " -- " + self.centro.nombre  + " (" + self.centro.departamento.nombre + " | " + self.centro.municipio.nombre + ")"

    def name_short(self):
        return "a"



#################SISTEMA ########################################
#
# class TblDepartmentsMunicipalities(models.Model):
#     id_distrito = models.AutoField(db_column='ID_DISTRITO', primary_key=True)  # Field name made lowercase.
#     name = models.CharField(db_column='NAME', max_length=1000)  # Field name made lowercase.
#     code_real = models.CharField(db_column='CODE_REAL', unique=True, max_length=4)  # Field name made lowercase.
#     id_depto = models.IntegerField(db_column='ID_DEPTO', blank=True, null=True)  # Field name made lowercase.
#     active = models.SmallIntegerField(db_column='ACTIVE', blank=True, null=True)  # Field name made lowercase.
#
#     class Meta:
#         managed = False
#         db_table = 'TBL_DEPARTMENTS_MUNICIPALITIES'
#
#
# class TblDocument(models.Model):
#     id_document = models.AutoField(db_column='ID_DOCUMENT', primary_key=True)  # Field name made lowercase.
#     doc_number = models.CharField(db_column='DOC_NUMBER', max_length=1000)  # Field name made lowercase.
#     b64_doc_code = models.TextField(db_column='B64_DOC_CODE')  # Field name made lowercase.
#     tipo_doc = models.TextField(db_column='TIPO_DOC')  # Field name made lowercase.
#     id_person = models.ForeignKey('TblPerson', models.DO_NOTHING, db_column='ID_PERSON')  # Field name made lowercase.
#     latitude = models.CharField(db_column='LATITUDE', max_length=1000)  # Field name made lowercase.
#     longitude = models.CharField(db_column='LONGITUDE', max_length=1000)  # Field name made lowercase.
#     create_date = models.DateField(db_column='CREATE_DATE')  # Field name made lowercase.
#     active = models.SmallIntegerField(db_column='ACTIVE', blank=True, null=True)  # Field name made lowercase.
#
#     class Meta:
#         managed = False
#         db_table = 'TBL_DOCUMENT'
#
# class TblPerson(models.Model):
#     id_person = models.AutoField(db_column='ID_PERSON', primary_key=True)  # Field name made lowercase.
#     name = models.CharField(db_column='NAME', max_length=500)  # Field name made lowercase.
#     id_number = models.CharField(db_column='ID_NUMBER', max_length=500)  # Field name made lowercase.
#     phone = models.CharField(db_column='PHONE', max_length=9)  # Field name made lowercase.
#     code_depto = models.ForeignKey(TblDepartmentsMunicipalities, models.DO_NOTHING, db_column='CODE_DEPTO', related_name='person_departamento')  # Field name made lowercase.
#     code_municipality = models.ForeignKey(TblDepartmentsMunicipalities, models.DO_NOTHING, db_column='CODE_MUNICIPALITY', related_name = 'persona_municipio')  # Field name made lowercase.
#     create_date = models.DateTimeField(db_column='CREATE_DATE')  # Field name made lowercase.
#     active = models.SmallIntegerField(db_column='ACTIVE', blank=True, null=True)  # Field name made lowercase.
#
#     class Meta:
#         managed = False
#         db_table = 'TBL_PERSON'
#
#
# class Acta(ModeloBase):
#     documento = models.ForeignKey(TblDocument,related_name='documento_acta', on_delete=models.CASCADE)
#     departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
#     municipio = models.ForeignKey(Municipio,on_delete=models.CASCADE)
#     tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)
#     mesa = models.CharField(max_length=64, unique=True)
#     #numero = models.CharField(max_length=150)
#     aldea  = models.CharField(max_length=150, null = True)
#     #origen = models.CharField(max_length=150)
#     descripcion = models.CharField(max_length=150)



class Escrutinio(ModeloBase):
    #TIPOS_CHOICES = [||
    #    ('C', 'Conteo'),
    #    ('VB', 'Votos Blancos'),
    #    ('VN', 'Votos Nulos'),
    #    ('GT', 'Gran Total'),
    #]
    mesa = models.ForeignKey(Mesa,related_name='mesa_votos',on_delete=models.CASCADE)
    #mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE,related_name='mesa_votos',verbose_name="Mesa")
    candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE, null= True)
    valor = models.IntegerField( max_length=15)


class Colaborador(ModeloBase):
    GENDER_CHOICES = [
        ('F', 'Femenino'),
        ('M', 'Masculino'),
    ]
    USER_CHOICES = [
        ('G', 'GENERAL'),
        ('D', 'DEPARTAMENTAL'),
        ('M', 'MUNICIPAL'),
    ]
    user = models.OneToOneField(User,related_name='colaborador_user', on_delete=models.CASCADE)
    municipio = models.ForeignKey(Municipio, related_name='municipio_usuario',on_delete=models.CASCADE)
    tipo = models.CharField(
        max_length=15,
        choices=USER_CHOICES,
    )
    identidad = models.CharField(max_length=150, null = True)
    nombre = models.CharField(max_length=150)
    sexo = models.CharField(
        max_length=15,
        choices=GENDER_CHOICES,
    )
    foto = models.ImageField(upload_to='media/usuarios',max_length=300)


    def __str__(self):
        return self.user.username + " - - " + self.municipio.nombre


class resumendata(models.Model):
    departamento_id = models.IntegerField()
    departamento = models.CharField(max_length=40)
    municipio_id = models.IntegerField()
    municipio = models.CharField(max_length=40)
    centro_id = models.IntegerField()
    centro = models.CharField(max_length=40)
    mesa_id = models.IntegerField()
    mesa = models.CharField(max_length=40)
    candidato_tipo = models.CharField(max_length=40)
    partido = models.CharField(max_length=40)
    candidato_id = models.IntegerField()
    candidato = models.CharField(max_length=40)
    votos = models.IntegerField()

main/forms.py
from main.models import *
from django import forms

class CandidatoCreateForm(forms.ModelForm):
    identidad = forms.CharField(required = False)
    class Meta:
        model = Candidato
        fields = [
                    'tipo',
                    'partido',
                    'identidad',
                    'nombre',
                    'Sexo',
                    'departamento',
                    'municipio',
                    #'telefono',
                    #'email',
                    #'direccion',
                    'foto',
                ]

class EscrutinioCreateForm(forms.ModelForm):
    #identidad = forms.CharField(required = False)
    class Meta:
        model = Escrutinio
        fields = [
                    'mesa',
                    'candidato',
                    'valor'
                ]
    def __init__(self, user, *args, **kwargs):
        super(EscrutinioCreateForm, self).__init__(*args, **kwargs)
        print('Al parecer sí vas al formulario')
        self.fields['centro'].queryset = CentroEducativo.objects.filter(pk =0)

class MesaCreateForm(forms.ModelForm):
    class Meta:
        model = Mesa
        fields = [
                'centro',
                'descripcion',
                'numero'
        ]

class ColaboradorCreateForm(forms.ModelForm):
    class Meta:
        model = Colaborador
        fields = [
                'municipio',
                'user',
                'tipo',
                'sexo',              
                'identidad',
                'nombre',
                'foto'

        ]
# class ActaCreateForm(forms.ModelForm):
#     identidad = forms.CharField(required = False)
#     class Meta:
#         model = Acta
#         fields = [
#                     'documento',
#                     'departamento',
#                     'municipio',
#                     'aldea',
#                     'tipo',
#                     'mesa',
#                     'descripcion',
#
#                 ]

templates/main/candidato_confirm_delete.html
<!DOCTYPE html>
{% extends 'base/base.html'%}
{% load widget_tweaks %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content%}
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Panel <span class="fw-300"><i>Home</i></span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                      {{ form.message.errors }}
                        <label for="{{ form.message.id_for_label }}">Your message:</label>
                      {{ form.message }}
                        <div class="panel-tag">
                            It stash and was even had of collection the latest story still every or times derive come way. Travelling business ill. Helplessly starting didn't should he her bad will so through audiences to the supported congress, if card with was way allows century quarter the control village for of payload.
                        </div>
                        <form method="post">{% csrf_token %}
                              <p>Seguro que desea borrar a  "{{ object }}"?</p>                        
                        <button class="btn btn-danger ml-auto waves-effect waves-themed" type="submit">Confirmar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

  {%  block script %}
  <script type="text/javascript">

    $(function () {
      {% if error  %}
      toastr.error('Error en el formulario, por favor verifique los campos')
      {% endif %}
      {% if exito  %}
      toastr.success('Formulario guardado con exito')
      {% endif %}
   })
  </script>
  {% endblock %}
  </body>
</html>

templates/main/candidato_form.html
<!DOCTYPE html>
{% extends 'base/base.html'%}
{% load widget_tweaks %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content%}
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Panel <span class="fw-300"><i>Home</i></span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                      {{ form.message.errors }}
                        <label for="{{ form.message.id_for_label }}">Your message:</label>
                      {{ form.message }}
                        <div class="panel-tag">
                            It stash and was even had of collection the latest story still every or times derive come way. Travelling business ill. Helplessly starting didn't should he her bad will so through audiences to the supported congress, if card with was way allows century quarter the control village for of payload.
                        </div>
                        <form class="needs-validation was-validated" novalidate="" method="post"  enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="form-row">
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Tipo de Candidato <span class="text-danger">*</span> </label>
                                {{ form.tipo|add_class:"form-control select2 select2-hidden-accessible" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Corriente <span class="text-danger">*</span> </label>
                                {{ form.partido|add_class:"form-control select2" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                            <div class="form-group">
                              <label  for="{{ form.identidad.id_for_label }}" class="form-label" for="validationTooltip01">Identidad  </label>
                                {{ form.identidad|add_class:"form-control" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                            </div>
                          </div>
                          </div>
                          <br>
                          <div class="form-row">
                          <div class="col-md-4 mb-3">
                              <div class="form-group">
                                <label  for="{{ form.nombre.id_for_label }}" class="form-label" for="validationTooltip01">Departamento <span class="text-danger">*</span> </label>
                                <select name="departamento" id="id_departamento" class="form-control select2 select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true" required>
                                  <option > ----  Seleccione  ----</option>
                                  {% for d in departamentos %}
                                    <option value="{{d.pk}}" >{{d.nombre}}</option>
                                  {% endfor %}
                                  </select>
                                <div class="valid-tooltip">
                                    Correcto!!!
                                </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Municipio <span class="text-danger">*</span> </label>
                              <select name="municipio" class="form-control select2" required="" id="id_municipio">
                                <option value="" selected="">---------</option>
                                {% for m in municipios %}
                                  <option value="{{m.pk}}" >{{m.departamento.nombre}} | {{m.nombre}}</option>
                                {% endfor %}
                              </select>
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          </div>
                          <br>
                          <div class="form-row">
                          <div class="col-md-4 mb-3">
                              <div class="form-group">
                                <label  for="{{ form.nombre.id_for_label }}" class="form-label" for="validationTooltip01">Nombre <span class="text-danger">*</span> </label>
                                  {{ form.nombre|add_class:"form-control" }}
                                <div class="valid-tooltip">
                                    Correcto!!!
                                </div>
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Sexo <span class="text-danger">*</span> </label>
                                {{ form.Sexo|add_class:"form-control select2 select2-hidden-accessible" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          </div>
                          <br>
                          <br>
                          <div class="form-row">
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="{{ form.foto.id_for_label }}">Fotografia <span class="text-danger">*</span> </label>
                                {{ form.foto|add_class:"form-control" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          </div>
                          <br>

                        <button class="btn btn-primary ml-auto waves-effect waves-themed" type="submit">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

  {%  block script %}
  <script type="text/javascript">

    $(function () {
      $('.select2').select2();
      {% if error  %}
      toastr.error('Error en el formulario, por favor verifique los campos')
      {% endif %}
      {% if exito  %}
      toastr.success('Formulario guardado con exito')
      {% endif %}
   })
  </script>
  {% endblock %}
  </body>
</html>

templates/main/mesa_form.html
<!DOCTYPE html>
{% extends 'base/base.html'%}
{% load widget_tweaks %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content%}
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Panel <span class="fw-300"><i>Home</i></span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                      {{ form.message.errors }}
                        <label for="{{ form.message.id_for_label }}">Your message: {{exito}}</label>
                      {{ form.message }}
                        <div class="panel-tag">
                            It stash and was even had of collection the latest story still every or times derive come way. Travelling business ill. Helplessly starting didn't should he her bad will so through audiences to the supported congress, if card with was way allows century quarter the control village for of payload.
                        </div>
                        <form class="needs-validation was-validated" novalidate="" method="post"  enctype="multipart/form-data">
                          {% csrf_token %}
                          <div class="form-row">
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Centro Educativo <span class="text-danger">*</span> </label>
                                {{ form.centro|add_class:"form-control select2" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                              <label class="form-label" for="validationTooltip01">Descripción <span class="text-danger">*</span> </label>
                                {{ form.descripcion|add_class:"form-control " }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                          </div>
                          <div class="col-md-4 mb-3">
                            <div class="form-group">
                              <label  for="{{ form.identidad.id_for_label }}" class="form-label" for="validationTooltip01">Número de Mesa  </label>
                                {{ form.numero|add_class:"form-control" }}
                              <div class="valid-tooltip">
                                  Correcto!!!
                              </div>
                            </div>
                          </div>
                          </div>
                          <br>



                        <button class="btn btn-primary ml-auto waves-effect waves-themed" type="submit">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

  {%  block script %}
  <script type="text/javascript">

    $(function () {
      $('.select2').select2();
      {% if error  %}
      {% if error == 2 %}
      toastr.error('La mesa ya existe, favor ingresar una mesa con un número diferente')
      {% else %}
      toastr.error('Error en el formulario, por favor verifique los campos')
      {% endif %}
      {% endif %}
      {% if exito  %}
      toastr.success('Formulario guardado con exito')
      {% endif %}
   })
  </script>
  {% endblock %}
  </body>
</html>